### ISSUE TITLE
Bugs in FuelLinesFrom and FuelLinesTo

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#193]
FuelLinesTo always returns "this" part in current implementation. So part.FuelLinesTo == part in all cases. Must return otherPart's list.

For proper fuel feed estimation, the Crossfeed property of the original fuel line part must be examined to check if the fuel line is enabled (decouplers and docking ports creates this fuel line links). There is no way to do this with parents. So FuelLinesFrom must return fuel line parts itself. Not it's parent.

[Part.cs.patch.txt](https://github.com/djungelorm/krpc/files/118755/Part.cs.patch.txt)

**Comment by djungelorm** [comment]
I don't think there is a bug here... FuelLinesTo needs to call x.parent otherwise it returns the fuel line part, not the part connected to the fuel line part. And your patch for FuelLinesFrom doesn't make sense to me.

Here's an example script:

```python
import krpc
conn = krpc.connect()
vessel = conn.space_center.active_vessel

for part in vessel.parts.all:
    print part.title
    print '  FuelLinesTo:'
    for connected_part in part.fuel_lines_to:
        print '    ', connected_part.title
    print '  FuelLinesFrom:'
    for connected_part in part.fuel_lines_from:
        print '    ', connected_part.title
    print
```

And here's an example craft file:
![craft](https://cloud.githubusercontent.com/assets/6644613/13036578/e2f3f6b2-d31f-11e5-80ce-b23b286491f9.png)
[fuellines.zip](https://github.com/djungelorm/krpc/files/129916/fuellines.zip) 

Running this produces the following output:
```
Mk1 Pod (2m)
  FuelLinesTo:
  FuelLinesFrom:
     1.25m Fuselage (Pressurized)

Modular Girder Segment XL
  FuelLinesTo:
  FuelLinesFrom:

1.25m Fuselage (Pressurized)
  FuelLinesTo:
  FuelLinesFrom:

FTX-2 External Fuel Duct
  FuelLinesTo:
     FTX-2 External Fuel Duct
  FuelLinesFrom:
```

This looks correct to me? Only potential issue is that the behavior is undefined when these methods are called for the fuel duct itself. Maybe that should throw an error instead?

Here's the output with your patch:
```
Mk1 Pod (2m)
  FuelLinesTo:
  FuelLinesFrom:
     FTX-2 External Fuel Duct

Modular Girder Segment XL
  FuelLinesTo:
  FuelLinesFrom:

1.25m Fuselage (Pressurized)
  FuelLinesTo:
  FuelLinesFrom:

FTX-2 External Fuel Duct
  FuelLinesTo:
     Mk1 Pod (2m)
  FuelLinesFrom:
```

**Comment by djungelorm** [comment]
I've made some changes that should fix the issue, producing the expected output described above.

Here's a copy of KRPC.SpaceCenter.dll with the fix applied if you'd like to try it:
[SpaceCenter.zip](https://github.com/djungelorm/krpc/files/131954/SpaceCenter.zip)
