### ISSUE TITLE
protocol improvement suggestions

### ISSUE THREAD

**Issue by Cahu** [krpc/krpc#264]
Hi,

I'm implementing a client in a language you don't already support. Here are a few suggestions to make writing a client a little easier.
- In protobuf v3, fields are 'optional' by default. When compiling the .proto file, the generated code checks for the presence of all these fields all the time. I think setting fields that are always present to 'required' will result in simpler code and possibly smaller messages.
- It might also be possible to merge some fields together. For instance, in the 'Response' message, both fields 'error' and 'has_error' are implicitly declared 'optional'. The two could be merged in one single 'optional' field that is present only if there was an error.
- I think primitive types returned as 'bytes' should be encapsulated inside a message. For instance:
  message resultFloat {
      required float value = 1;
  }
  It might seem a bit odd but that would allow client implementation not to have to call the de-serializer for these types by hand (when retrieving the result of a 'Response' message for example). That would be very helpful if your protocol-buffer implementation does not expose the functions it uses to (de-)serialize primitive types.

**Comment by djungelorm** [comment]
1) I had a look into this, and required fields aren't possible in proto3. There are only two types of field: optional (the default) and repeated.

2) Makes sense. I'll see what's required to make the changes. Looks like it should be possible to get rid of all the has_ fields

3) This would add redundant data to the binary for messages, and probably have a negative impact on performance. For example, returning an integer would require an additional byte (for the tag and wire type). This might not seem significant for a response message containing a single integer, but it would be significant for collections of primitive types. I guess this is a trade-off between ease of implementing the clients vs message size and performance. I'm tempted to go for minimizing message size as we want the RPC execution rate to be as high as possible so that scripts can poll values with minimal overhead.

**Comment by djungelorm** [comment]
Closing, as (1) and (2) have been implemented and I am not implementing (3) as discussed above.
