### ISSUE TITLE
Expose information on connected clients and connection events

### ISSUE THREAD

**Issue by dewiniaid** [krpc/krpc#304]
Per our discussion [here](http://forum.kerbalspaceprogram.com/index.php?/topic/130742-113-krpc-control-the-game-using-c-c-java-lua-python-ruby-haskell-v035-25th-june-2016/&page=5#comment-2669254), it would be useful if other KSP mods could examine a list of clients connected to KRPC and subscribe to the events generated when clients connect and disconnect.  My particular use case is in the kOS/kRPC bridge, but there may be others.

It would probably also be useful to expose this information (at least the client list itself) to clients as well, e.g. to see who is connected.

**Comment by jwvanderbeck** [comment]
This would definitely be useful, especially the ability to recognize a client disconnect so that they can clean things up.

**Comment by djungelorm** [comment]
I've made the following changes:

- Connected clients and server events (and other useful APIs) can be accessed via the object returned by property ```KRPC.Core.Instance```
- Added a ```KRPC.Clients``` RPC that returns a list of connected clients (so that client programs can see what clients are connected)

Also, the client that called an RPC can be obtained (within the code for the RPC) via property ```KRPC.Server.CallContext.Client```. This is feature was already present in kRPC, just wasn't very well documented...

**Comment by djungelorm** [comment]
Changes have been merged to master. Let me know if there's anything you want added/changed in the API!
