### ISSUE TITLE
Invalid Part::decouple_stage values for some plugin parts

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#307]
If part is a decupler, it can be decupled in two ways when activeted:
1. Decouple everyting below it in the parts tree and decouple itself (that is assumed now).
2. Decouple everyting below only, NOT itself.
Some parts from some plugins uses second method of decoupling, so when this part is activated, it is not decoupled, but decouples everything below it. For example, "Breeze-M Droptank" from "Proton-M / Breeze-M" mod. This is a fuel tank, but also, it is a decoupler. Third stage of the rocket is attached directly to it, and it decouples this stage from itself when activated. But kRPC decouple_stage for it, always equal to the activation stage. May be i missing something, but there is no way to get right decoupling sequence with this parts.

I am writing (finished and testing now) a very complex system based on kRPC for automated rocket launch control using optimum trajectory (yep, realy optimum, solved from differential equaetions of moition and optimality conditions by NLP solver), and right decoupling sequence is a very important thing in my case. I hope we can solve this...

**Comment by Assert1** [comment]
[env.ckan.txt](https://github.com/krpc/krpc/files/360095/env.ckan.txt)
[Breez-M + Proton-M GSO T.craft.txt](https://github.com/krpc/krpc/files/360096/Breez-M.Proton-M.GSO.T.craft.txt)

**Comment by Assert1** [comment]
If you look at Breez-M + Proton-M GSO T.craft file, part HGABreezeTank_4292720392 have 
istg = 3 and dstg = 1
That look as activation stage and decoupling stage. But kRPC return 3 for stage() and 3 instead of 1 for decouple_stage().

**Comment by djungelorm** [comment]
Thanks for the bug report! Things are more complex than I first thought....

Currently, the decouple stage for a part is calculated by walking the parts tree, from the part in question towards the root part, until a decoupler is found. The value returned is then the activation stage of the decoupler.

As far as I can tell the decouple stage for a part is not provided in the craft file or via the KSP API, so we have to calculate it from the parts tree.

There are two things wrong with the current approach:
1. As you point out, it needs to check which side of the decoupler fires. Some decouplers also fire on both sides. This is an easy fix - just need to check the "ExplosiveNode" property of the decoupler.
2. More complicated to fix is that the current code walks the tree from the part in question towards the root part. Instead, it should walk the tree towards the _controlling part_. This is because when a decoupler fires, the resulting vessel is the group of parts that contains the controlling part.

**Comment by djungelorm** [comment]
I think I've figured out what dstg is. It is related to the decouple stage we want, but is not quite the same. I think it's coincidence that it has the desired value for your example rocket...

For example a rocket with:
```pod -> decoupler  (fires in stage 0) -> tank -> tank -> engine -> decoupler (fires in stage 1) -> tank -> engine```
will have dstgs as follows (regardless of which side of the decoupler fires):
```0 -> 1 -> 2 -> 2 -> 2 -> 3 -> 4 -> 4```
but the desired decouple stage values would be:
```-1 -> 0 -> 0 -> 0 -> 0 -> 1 -> 1 -> 1```

dstg is also relative to the root part, not the controlling part, so has the same issue 2 as above.

**Comment by djungelorm** [comment]
Here's a dev version with issue 1 fixed. Should fix the issue with your craft (I don't have time right now to try it with your heavily modded install, but have tested it with some similar stock parts)
https://krpc.s3.amazonaws.com/deploy/bug/part-decouple-stage/588.1/krpc-0.3.5-25-g4c29f79.zip

**Comment by Assert1** [comment]
For example rocket hierarchy is:
`breez-M core -> (decouples) outer breez-M tank -> (decouples) fairing base ... stage 3 tank and engies`
'                       -> payload decoupler -> (decouples) test payload'
'                       -> breez-M engines'
To be more accurate.

May be it is enought to assume _controlling part_ as the root part (that is true by default) for begining.

**Comment by djungelorm** [comment]
Yeah I agree we should just assume controlling part == root part for now. If the issue comes up in the future we can have another look at it.

**Comment by djungelorm** [comment]
Found another minor issue (and fixed it). The decouple stage number was wrong when a decoupler fires before a decoupler below it. This is an odd staging setup but good to cover all eventualities!

For example:
```pod -> decoupler1 -> tank -> decoupler2 -> engine```
If decoupler1 fires in stage 1 _before_ decoupler2 in stage 0, the numbering should be:
```-1 -> 1 -> 1 -> 1 -> 1```
but if decoupler1 fires in stage 0 _after_ decoupler2 in stage 1 it should be:
```-1 -> 0 -> 0 -> 1 -> 1```
