### ISSUE TITLE
Latest (0.3.7)krpc python client library crashes on import

### ISSUE THREAD

**Issue by tuokor** [krpc/krpc#376]
If I install the latest krpc client library using ```pip install krpc``` and try to import krpc module I will get this crash:
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tuomas/work/kerbal-controller/testenv/lib/python3.5/site-packages/krpc/__init__.py", line 2, in <module>
    from krpc.client import Client
  File "/home/tuomas/work/kerbal-controller/testenv/lib/python3.5/site-packages/krpc/client.py", line 11, in <module>
    import krpc.schema.KRPC
  File "/home/tuomas/work/kerbal-controller/testenv/lib/python3.5/site-packages/krpc/schema/KRPC.py", line 42, in <module>
    options=None),
  File "/home/tuomas/work/kerbal-controller/testenv/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```
However if I install the client library directly from sourcecode (as of writing the latest commit was 2f4d3be) this crash doesn't happen.

**Comment by djungelorm** [comment]
I've also come across this issue, but I think it is a bug with the python protobuf library.

I get this exact error on my Ubuntu system with the python client v3.2.0, and libprotobuf.so v3.2.0, and thhe apt package libprotobuf9v5 installed (which contains a much older version of libprotobuf.so)

On my other system which does not have libprotobuf9v5 installed, I don't get this problem.

A workaround for this issue is to force the python client to use a python implementation instead of libprotobuf.so by setting the environment variable ``PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION`` to ``python``.

**Comment by tuokor** [comment]
Does the latest code from master use the python implementation since it works?

**Comment by djungelorm** [comment]
No it uses the cpp implementation by default.

The only important difference I can think of is that the latest code is built against protobuf 3.2.0.

v0.3.7 is built against protobuf 3.1.0, so maybe try forcing pip to install that version instead of the latest protobuf, e.g. using the following?
```
pip install --upgrade protobuf==3.1.0
pip install krpc
```

**Comment by tuokor** [comment]
Yes that solves the problem.
