### ISSUE TITLE
Unfocused wheel steering only works once

### ISSUE THREAD

**Issue by postalbyke** [krpc/krpc#388]
[Python] While attempting to operate a rover remotely, I noticed that the unfocused rover only turns circles. Further investigation shows I can only change the wheel_steering once. wheel_steering is unresponsive after the first command until the rover becomes focused.

**Comment by djungelorm** [comment]
I have managed to reproduce the issue, and am working on a fix. Thanks!

**Comment by postalbyke** [comment]
Swanky!
I'm working on learning anything about anything, so I'd like to know where you think the problem is so I can look at the code.

**Comment by djungelorm** [comment]
This one was a bit subtle, but basically the PIlotAddon (the code for which is here: https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/PilotAddon.cs) runs some code on every game tick to update the vessel/rovers control inputs.

This was continually incrementing the wheel steer value, rather than setting it, so when control.wheel_steer was set to 1, it would increase the vessels wheel steer control by 1 on each tick (without bound!). This meant that the longer you had control.wheel_steering set to 1, the higher it's value would be. So when setting control.wheel_steering set to -1, it would take some time to get back to zero and go negative before you saw any change in the wheel direction.

The same was also true for wheel_throttle

**Comment by postalbyke** [comment]
Legit! I had always wondered adding a boolean was an efficient solution for my problems like this.
Also, I'm looking forward to driving several rovers at once :-D 
Thank you!

**Comment by djungelorm** [comment]
No problemo!

Btw, if you want to try out the changes now, you can grab a pre-release build from the continuous integration server: https://krpc.s3.amazonaws.com/deploy/master/885.1/krpc-0.3.9-17-ge29b0bb.zip
