### ISSUE TITLE
Specify when a call can return 'null' in .json service definition files

### ISSUE THREAD

**Issue by Cahu** [krpc/krpc#395]
In KRPC.SpaceCenter.json there are definitions like this where the return value can be null according to the documentation:
```
      "Part_get_Fairing": {
        "parameters": [ { ... } ],
        "return_type": {
          "code": "CLASS",
          "service": "SpaceCenter",
          "name": "Fairing"
        },
        "documentation": "<doc>\n<summary>\nA <see cref=\"T:SpaceCenter.Fairing\" /> if the part is a fairing, otherwise <c>null</c>.\n</summary>\n</doc>"
```
In order to generate the correct code for this rpc call in languages that don't have a 'null', it would be useful to have this information encoded in some way. For instance:
```
        "return_type": {
          "code": "CLASS",
          "service": "SpaceCenter",
          "name": "Fairing",
          "optional": true
        },
```

**Comment by djungelorm** [comment]
I can see how that could be useful, will look into adding it for v0.4. Maybe call the property "nullable" instead though to be clearer what it is exactly.

**Comment by djungelorm** [comment]
I've added this feature :) I've named the field "nullable".

Note that I had to manually annotate the methods that might return null in the service code, as there is no simple way in C# to automatically detect if a method will return null. So there may be methods I've missed!

A pre-release is build available here (also updated for KSP 1.3):
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/v0.4.0-feature/nullable/920.1/

**Comment by djungelorm** [comment]
The changes have been merged into the v0.4.0 branch. Thanks!

**Comment by TeWu** [comment]
I've just checked for protobuf schema update (which is an item in my "before release checklist" for [kRPC-rb][1]), and noticed this new, funny `nullable` field ;)

Based on what I can see in the [relevant commit][2], I'm led to believe that client libraries are not expected to set a value of this field at any point, and can treat it as read-only field. Could you please confirm that?

[1]: https://github.com/TeWu/krpc-rb
[2]: https://github.com/krpc/krpc/pull/325/commits/610a10009c489663eb2cd51ca274f8303ff64f56

**Comment by djungelorm** [comment]
Yes it can be treated as "read-only". It is part of the `Type` message - which is only sent to clients, never the server.

**Comment by TeWu** [comment]
Unfortunately this new `nullable` field is causing [kRPC-rb][1] the [issue][3]. I believe Python client has the same issue [here][4].

It could be fixed in the clients code, but I think that this new `nullable` field doesn't really belong to `Type` message. For example `nullable` field isn't used for parameter types, but have a value of `false` for those types. Which lead to strange looking inconsistencies, like those when getter for an attribute has return type with `nullable: true`, but setter for this attribute has a parameter with `nullable: false`, e.g: 

```ruby
### Excuse me use of Ruby for this illustration
[14] pry(main)> client.krpc.get_services.services.select{|s| s.name == "SpaceCenter" }[0].procedures.select {|p| p.name =~ /_TargetBody/ }
=> [<KRPC::PB::Procedure: name: "get_TargetBody", parameters: [], return_type: <KRPC::PB::Type: code: :CLASS, service: "SpaceCenter", name: "CelestialBody", types: [], nullable: true>, documentation: "<doc>\n<summary>\nThe currently targeted celestial body.\n</summary>\n</doc>">,
    <KRPC::PB::Procedure: name: "set_TargetBody", parameters: [<KRPC::PB::Parameter: name: "value", type: <KRPC::PB::Type: code: :CLASS, service: "SpaceCenter", name: "CelestialBody", types: [], nullable: false>, default_value: "">], return_type: nil, documentation: "<doc>\n<summary>\nThe currently targeted celestial body.\n</summary>\n</doc>">]
```

Instead of fixing clients code, I would propose one of the following change to protobuf schema:

* Create `ReturnType` message and move `nullable` field there. Then use `ReturnType` message as a type of `Procedure.return_type` field.
* Move the `nullable` field to the `Procedure` message, and possibly rename it to `is_return_type_nullable`. This is my personal favorite solution :+1:.

[1]: https://github.com/TeWu/krpc-rb
[2]: https://github.com/TeWu/krpc-rb/blob/b9979d3fa6017cd712ca2634ff810222d31ec6fe/lib/krpc/types.rb#L32-L34
[3]: https://github.com/TeWu/krpc-rb/issues/13
[4]: https://github.com/krpc/krpc/blob/67aebf79ebfa670d442ca88fa2270704bb8ab107/client/python/krpc/types.py#L59

**Comment by djungelorm** [comment]
Ah yes you're right... I'm away these next two weeks so can't get anything implemented right now though :(

And I agree I think the second option is best.

**Comment by TeWu** [comment]
I'm glad you agree :smile:; and don't worry about it, it's not breaking client libraries, just making them consume a little more memory than absolutely necessary.

**Comment by djungelorm** [comment]
I've moved the boolean field to `Procedure.return_is_nullable` in the protobuf schema and JSON service definition files. The changes are on the v0.4.0 branch.
