### ISSUE TITLE
magnitude of y and z components of the velocity vector maybe wrong

### ISSUE THREAD

**Issue by mkluge** [krpc/krpc#398]
While running this example:
https://krpc.github.io/krpc/tutorials/reference-frames.html#surface-speed
i have reduced (according to FlightEngineer and what I see on the NavBall) my horizontal speed to about 3 m/s. Still the surface velocity is measured as:
Surface velocity = (-104.8, -4.2, 31.6)
Should'nt be the y and the z component of this vector closer to zero? So that horz_speed=sqrt(y^2+z^2)?
I would guess that either I miss something or the values are not correct.

**Comment by mkluge** [comment]
using a custom reference frame:
ref_frame = vessel.orbit.body.reference_frame
frame = conn.space_center.ReferenceFrame.create_hybrid(position=ref_frame, rotation=vessel.surface_reference_frame)

gives correct readings. Not sure if this is a bug or indended.

**Comment by djungelorm** [comment]
This is intended behaviour. The values are like that because the y axis is in the direction from the center of the planet to the north pole, and the z axis is from the center of the planet to the point of the planets surface where 90 degree longitude and the equator meet (see this diagram https://krpc.github.io/krpc/tutorials/reference-frames.html#celestial-body-reference-frame).

The example was just to show how to get the speed relative to the surface, not the horizontal/vertical components of this speed.

If you want horizontal speed, you can either use a custom reference frame as above, or obtain it directly using vessel.flight().horizontal_speed (http://krpc.github.io/krpc/python/api/space-center/flight.html#SpaceCenter.Flight.horizontal_speed) 

I should probably add some more explanation to the example, or even change the example to use your custom frame as it makes more intuitive sense.
