### ISSUE TITLE
Why is the SpaceCenter service only available in the Flight gamescene?

### ISSUE THREAD

**Issue by jimbofreedman** [krpc/krpc#430]
I'd like to be able to launch vessels without already having an active vessel. I'm thinking of cloning and building this myself but was wondering if you had already attempted this.

**Comment by djungelorm** [comment]
Mainly because most of the functionality is only available in the flight scene, but I agree this RPC should be available in other scenes. I've not attempted this before, but should be an easy change.

I think a nice way to implement this would be to add a GameScene parameter to the RPC attributes (such as KRPCMethod and KRPCProcedure). That way, the SpaceCenter service can be marked as only available in the flight scene (via the KRPCService attribute), but specific RPCs can override this restriction.

**Comment by djungelorm** [comment]
This has been added in v0.4.8. See #471

**Comment by nevercast** [comment]
This is exciting, time to update! Thanks!

**Comment by djungelorm** [comment]
It's been released :)
