### ISSUE TITLE
All service IDs are equal to 2 in JSON files describing schema in tarball for 0.4.3

### ISSUE THREAD

**Issue by Shimuuar** [krpc/krpc#433]
That's probably a bug in build since they aren't part of repository. I guess cnano client should be broken because of this but I never tested this

**Comment by djungelorm** [comment]
Thanks for spotting this. Ids were being assigned sequentially as each services was loaded, but the service definition file generator is run independently for each service so they all ended up with the same id in the definition file.

I've changed it so that if an id is not specified explicitly in the code, it is generated from a hash of the services name, with a very low probability of collision.
