### ISSUE TITLE
Incorrect server-side type conversion for parts

### ISSUE THREAD

**Issue by eXigentCoder** [krpc/krpc#447]
Thanks once again for an amazing mod!

Upgrading [krpc-node](https://github.com/eXigentCoder/krpc-node) to use the new async/await syntax in JavaScript got me really excited about krpc again so I started putting together a [mission to launch a DeLorean to space on a Falcon 9 Heavy](https://github.com/eXigentCoder/krpc-node-examples/tree/master/src/Launch-At-Dawn).

In the process I think I might have uncovered a bug, i've managed to reproduce it two separate ways. This is using `1.3.1.1891 (LinuxPlayer)` version of the game on Ubuntu 17.10 with `kRPC v0.4.4` over web sockets with `krpc-node v4.0.1`. 
Both methods result in the same error and method 1 and 2 are [checked in along with the mod list and crafts](https://github.com/eXigentCoder/krpc-node-examples/blob/master/src/Launch-At-Dawn/index.js).
```
Incorrect argument type for parameter this in SpaceCenter.Part_get_Name. Expected an argument of type KRPC.SpaceCenter.Services.Parts.Part, got KRPC.SpaceCenter.Services.Parts.Engine
  at KRPC.Service.Services.GetArguments (KRPC.Service.Scanner.ProcedureSignature procedure, IList`1 arguments) [0x00000] in <filename unknown>:0 
  at KRPC.Service.Services.ExecuteCall (KRPC.Service.Scanner.ProcedureSignature procedure, KRPC.Service.Messages.ProcedureCall call) [0x00000] in <filename unknown>:0 
  at KRPC.Service.ProcedureCallContinuation.Run () [0x00000] in <filename unknown>:0 
  at KRPC.Service.RequestContinuation.Run () [0x00000] in <filename unknown>:0 
  at KRPC.Core.ExecuteContinuation (KRPC.Service.RequestContinuation continuation) [0x00000] in <filename unknown>:0 
```

## Method 1

- Call `SpaceCenter.get_ActiveVessel` to get the current active vessel.
- Call `SpaceCenter.Vessel_get_Parts` passing in the current vessel.
- Call `SpaceCenter.Parts_WithTitle` passing in the parts object and the title of an engine part and get back an array of results.
- Take the first item in the result array and call `SpaceCenter.Part_get_Engine` passing in the part
- Above Error is thrown.

## Method 2

- Call `SpaceCenter.get_ActiveVessel` to get the current active vessel.
- Call `SpaceCenter.Vessel_get_Parts` passing in the current vessel.
- Call `SpaceCenter.Parts_get_Engines` passing in the parts object and get back an array of results.
- Take the first item in the result array and call `SpaceCenter.Engine_get_Part` passing in the id of the engine
- Note that the id of the part and engine are different. I'm assuming this is correct since they represent different objects in memory?
- Call `SpaceCenter.Part_get_Name` passing in the part.
- Above Error is thrown. (Passing in the engine id to `SpaceCenter.Part_get_Name` gives an identical error)

### PS
Is this docker image yours? https://hub.docker.com/r/krpc/buildenv/ Would I be able to use it to test my node library on a CI server?

Thanks again!

**Comment by djungelorm** [comment]
Just tried this using the python client and it seems to work fine:

```
import krpc
conn = krpc.connect()

# Method 1
vessel = conn.space_center.active_vessel
parts = vessel.parts
array = parts.with_title('RT-10 "Hammer" Solid Fuel Booster')
first = array[0]
print(first.engine)

# Method 2
vessel = conn.space_center.active_vessel
parts = vessel.parts
array = parts.engines
first = array[0]
part = first.part
print(part.name)
```

The part and engine objects are indeed different objects in memory with different id numbers. kRPC doesn't do polymorphism, which is why there is a general Part class for all parts and part-type-specific classes like Engine for additional functionality. Maybe the node client is confusing the two id numbers at some point and passing an engine object id to Part_get_Name?

That docker image is maintained by me. It's used to run CI tests on Travis CI, using these scripts:
https://github.com/krpc/krpc/blob/master/tools/travis-ci/script.sh
https://github.com/krpc/krpc/blob/master/tools/travis-ci/script-docker.sh
The image contains the build environment needed to compile and run kRPC and test all the clients against the TestServer. You could certainly use it to run tests for the node client, but might need to extend the image to install any dependencies for krpc-node.

**Comment by eXigentCoder** [comment]
Thanks, the bug must have been introduced on my side then, I'll do a bit more digging and see what I can uncover!
