### ISSUE TITLE
krpc 0.4.8 does not connect successfully with KSP 1.8 or 1.9

### ISSUE THREAD

**Issue by cknowles2112** [krpc/krpc#557]
KRPC appears to be working, but when trying to connect from python, the connect hangs and does not return.  Reverting KSP to 1.7, and connection works.

**Comment by Tastaturtaste** [comment]
I got the same issue, below is some additional information and a workaround that worked for me.
I use ksp v1.8.1 and krpc v0.4.8

**Workaround:**
Turning on auto-accept in the advanced server settings seems to circumvent the issue and I was able to connect normally.

**Additional Info:**
Turning on the debug logging for the server reveals some kind of TargetExeption when trying to connect to the server: [krpc_log_request_connection.txt](https://github.com/krpc/krpc/files/3852563/krpc_log_request_connection.txt)

Since turning on auto-accept circumvents the issue for me and in the exception logs some UI related stuff pops up, the problem maybe/probably lies somewhere within the accept-promt code.

**Comment by cknowles2112** [comment]
So, yes, setting to auto accept does allow connections to go through - but something is still going on - code that I had that works on 1.7.3 starts acting very odd in 1.8.x - as if many things arrive all at the same time rather than sequentially.  (I'm using krpc to build a simpit ... if I hit my "throttle up, enable SAS, stage" nothing happens, and then all three happen at once all together.)  One question, where's the logging stored?  (I've got it enabled, but I'm not seeing any logs in the krpc folder under gamedata.)

**Comment by Tastaturtaste** [comment]
The logging is stored in the KSP.log file in the KSP folder.

**Comment by cknowles2112** [comment]
So I see the entries that you refer to - but nothing around the problems I'm seeing after upgrading to kerbal 1.8.  The way it's acting is as if there's some lag.  When I fall back to 1.7.3 all works as expected.

**Comment by cknowles2112** [comment]
I have successfully worked around by command problems by adding a 2 second pause after connecting the program to KRPC.  However, the text box issues (not displaying) continue.

**Comment by djungelorm** [comment]
Fixed by #585
However, we now only support KSP 1.10
