### ISSUE TITLE
pip install failure + workaround

### ISSUE THREAD

**Issue by mdbernard** [krpc/krpc#624]
`pip install krpc` no longer works.

This appears to be due to `client/python/setup.py` no longer working due to the following issues with the call to `setup`:
- Cannot find `krpc/version.py` for `version` keyword argument (file does not exist)
- Cannot find `README.md` for `long_description` keyword argument (file does not exist)
- `use_2to3` is an invalid keyword argument
- Positional argument `{typed_files}` follows keyword arguments

By simply deleting the `long_description`, `use_2to3`, `{typed_files}` lines and setting the version to the string `'0.4.9'`, I was able to manually run `python setup.py install` into my virtual environment.

**Comment by JoseAntonioToralLopez** [comment]
Hi, where do you find `{typed_files}`?

I get to install, but when i import i get `NameError: name 'long' is not defined`

**Comment by mordavidj** [comment]
Hi @JoseAntonioToralLopez,

> Hi, where do you find `{typed_files}`?

@mdbernard is talking specifically about the [`client/python/setup.py`](https://github.com/krpc/krpc/blob/master/client/python/setup.py) in the current repository.

> I get to install, but when i import i get `NameError: name 'long' is not defined`

That is because you are using Python 3 where the `long` datatype doesn't exist. You can either use Python 2 or fork the repo and tweak a few things to get it to work.
