### ISSUE TITLE
Error while first using kRPC

### ISSUE THREAD

**Issue by EhSonvn** [krpc/krpc#625]
I've just installed krpc using pip, and downloaded the mod. But when I run these codes:
`import krpc
conn = krpc.connect()
print(conn.krpc.get_status().version)
`
I got them from the official documentations page, and got this error:
`Traceback (most recent call last):
  File "C:\Users\soner\source\repos\KSP\KSP\KSP.py", line 1, in <module>
    import krpc
  File "C:\Users\soner\AppData\Local\Programs\Python\Python311\Lib\site-packages\krpc\__init__.py", line 1, in <module>
    from krpc.connection import Connection
  File "C:\Users\soner\AppData\Local\Programs\Python\Python311\Lib\site-packages\krpc\connection.py", line 3, in <module>
    from krpc.encoder import Encoder
  File "C:\Users\soner\AppData\Local\Programs\Python\Python311\Lib\site-packages\krpc\encoder.py", line 9, in <module>
    from krpc.types import \
  File "C:\Users\soner\AppData\Local\Programs\Python\Python311\Lib\site-packages\krpc\types.py", line 10, in <module>
    KRPC.Type.SINT64: long,
NameError: name 'long' is not defined
`
What should I do? Is the mod deprecated? Thanks.

**Comment by balthazarSai** [comment]
I had a similar experience recently while trying to use kRPC. The problem is that long is not a thing in python 3.x and the package is trying to define a type as long [here](https://github.com/krpc/krpc/blob/master/client/python/krpc/types.py) on lines 7-15.

Even fixing this issue manually by swapping long with int will not get the mod to run properly and you will face other compatibility issues down the line. I don't know if this mod is supported but with KSP2 coming out very soon I don't think there's going to be many changes. I recommend trying to interface with KSP using C# as shown [here](https://www.youtube.com/watch?v=ilWZjYx7brE&t=4s) .

**Comment by EhSonvn** [comment]
Thank you for helping me out with this. I fixed those errors yesterday, but after reading your comment, I think I should just switch to the C# version. Have a nice day!

**Comment by ThomasWMarshall** [comment]
How exactly did you install krpc using pip? I installed it on Python 3.11.1 in a fresh venv with the following packages:

```
Package    Version
---------- -------
krpc       0.4.8
pip        22.3.1
protobuf   3.20.0
setuptools 57.0.0
```

Note that both seruptools and protobuf are downgraded.

So the steps to do this would be:

```
pip uninstall setuptools
pip install setuptools==57.0.0
pip install krpc
pip uninstall protobuff
pip install protobuf 3.20.0
```

**Note:** To anyone trying this, I strongly recommend doing this in a fresh venv so as not to mess with your real python install (https://docs.python.org/3/library/venv.html).


After that, I ran

`import collections`
`collections.Iterable = collections.abc.Iterable`

in the interpreter and from there the getting started tutorial worked for me.
